// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: body.proto

package body

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBodysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBodysRequest) Reset() {
	*x = GetBodysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBodysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBodysRequest) ProtoMessage() {}

func (x *GetBodysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBodysRequest.ProtoReflect.Descriptor instead.
func (*GetBodysRequest) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{0}
}

type GetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetByIdRequest) Reset() {
	*x = GetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRequest) ProtoMessage() {}

func (x *GetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bodyid  string  `protobuf:"bytes,1,opt,name=Bodyid,proto3" json:"Bodyid,omitempty"`
	Weight  float32 `protobuf:"fixed32,2,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Muscle  float32 `protobuf:"fixed32,3,opt,name=Muscle,proto3" json:"Muscle,omitempty"`
	FatRate float32 `protobuf:"fixed32,4,opt,name=FatRate,proto3" json:"FatRate,omitempty"`
}

func (x *Body) Reset() {
	*x = Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{2}
}

func (x *Body) GetBodyid() string {
	if x != nil {
		return x.Bodyid
	}
	return ""
}

func (x *Body) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Body) GetMuscle() float32 {
	if x != nil {
		return x.Muscle
	}
	return 0
}

func (x *Body) GetFatRate() float32 {
	if x != nil {
		return x.FatRate
	}
	return 0
}

type GetBodyByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *Body `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GetBodyByIdResponse) Reset() {
	*x = GetBodyByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBodyByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBodyByIdResponse) ProtoMessage() {}

func (x *GetBodyByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBodyByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBodyByIdResponse) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{3}
}

func (x *GetBodyByIdResponse) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetBodysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body []*Body `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
}

func (x *GetBodysResponse) Reset() {
	*x = GetBodysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBodysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBodysResponse) ProtoMessage() {}

func (x *GetBodysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBodysResponse.ProtoReflect.Descriptor instead.
func (*GetBodysResponse) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{4}
}

func (x *GetBodysResponse) GetBody() []*Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type CreateBodyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *Body `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *CreateBodyRequest) Reset() {
	*x = CreateBodyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBodyRequest) ProtoMessage() {}

func (x *CreateBodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBodyRequest.ProtoReflect.Descriptor instead.
func (*CreateBodyRequest) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBodyRequest) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type UpdateBodyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *Body `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *UpdateBodyRequest) Reset() {
	*x = UpdateBodyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBodyRequest) ProtoMessage() {}

func (x *UpdateBodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBodyRequest.ProtoReflect.Descriptor instead.
func (*UpdateBodyRequest) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBodyRequest) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type DefaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DefaultResponse) Reset() {
	*x = DefaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResponse) ProtoMessage() {}

func (x *DefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResponse.ProtoReflect.Descriptor instead.
func (*DefaultResponse) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{7}
}

func (x *DefaultResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_body_proto protoreflect.FileDescriptor

var file_body_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x42, 0x6f, 0x64, 0x79, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x42, 0x6f, 0x64, 0x79, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x4d, 0x75, 0x73, 0x63, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x4d, 0x75, 0x73, 0x63, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x61, 0x74, 0x52, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x46, 0x61, 0x74, 0x52, 0x61, 0x74,
	0x65, 0x22, 0x35, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x42, 0x6f,
	0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x32, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x64, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x6f, 0x64,
	0x79, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x33, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x33, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x29, 0x0a, 0x0f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0xc9, 0x02, 0x0a, 0x0b, 0x42, 0x6f, 0x64, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x40, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x14, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x73, 0x12,
	0x15, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x64, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x17,
	0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x17,
	0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14,
	0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a,
	0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x64, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_body_proto_rawDescOnce sync.Once
	file_body_proto_rawDescData = file_body_proto_rawDesc
)

func file_body_proto_rawDescGZIP() []byte {
	file_body_proto_rawDescOnce.Do(func() {
		file_body_proto_rawDescData = protoimpl.X.CompressGZIP(file_body_proto_rawDescData)
	})
	return file_body_proto_rawDescData
}

var file_body_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_body_proto_goTypes = []interface{}{
	(*GetBodysRequest)(nil),     // 0: body.GetBodysRequest
	(*GetByIdRequest)(nil),      // 1: body.GetByIdRequest
	(*Body)(nil),                // 2: body.Body
	(*GetBodyByIdResponse)(nil), // 3: body.GetBodyByIdResponse
	(*GetBodysResponse)(nil),    // 4: body.GetBodysResponse
	(*CreateBodyRequest)(nil),   // 5: body.CreateBodyRequest
	(*UpdateBodyRequest)(nil),   // 6: body.UpdateBodyRequest
	(*DefaultResponse)(nil),     // 7: body.DefaultResponse
}
var file_body_proto_depIdxs = []int32{
	2, // 0: body.GetBodyByIdResponse.body:type_name -> body.Body
	2, // 1: body.GetBodysResponse.body:type_name -> body.Body
	2, // 2: body.CreateBodyRequest.body:type_name -> body.Body
	2, // 3: body.UpdateBodyRequest.body:type_name -> body.Body
	1, // 4: body.BodyService.GetBodyById:input_type -> body.GetByIdRequest
	0, // 5: body.BodyService.GetBodys:input_type -> body.GetBodysRequest
	5, // 6: body.BodyService.CreateBody:input_type -> body.CreateBodyRequest
	6, // 7: body.BodyService.UpdateBody:input_type -> body.UpdateBodyRequest
	1, // 8: body.BodyService.DeleteBody:input_type -> body.GetByIdRequest
	3, // 9: body.BodyService.GetBodyById:output_type -> body.GetBodyByIdResponse
	4, // 10: body.BodyService.GetBodys:output_type -> body.GetBodysResponse
	7, // 11: body.BodyService.CreateBody:output_type -> body.DefaultResponse
	7, // 12: body.BodyService.UpdateBody:output_type -> body.DefaultResponse
	7, // 13: body.BodyService.DeleteBody:output_type -> body.DefaultResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_body_proto_init() }
func file_body_proto_init() {
	if File_body_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_body_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBodysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBodyByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBodysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBodyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBodyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_body_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_body_proto_goTypes,
		DependencyIndexes: file_body_proto_depIdxs,
		MessageInfos:      file_body_proto_msgTypes,
	}.Build()
	File_body_proto = out.File
	file_body_proto_rawDesc = nil
	file_body_proto_goTypes = nil
	file_body_proto_depIdxs = nil
}
