// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: body.proto

package body

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetByIdRequest) Reset() {
	*x = GetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRequest) ProtoMessage() {}

func (x *GetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBodyByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bodyid  string  `protobuf:"bytes,1,opt,name=Bodyid,proto3" json:"Bodyid,omitempty"`
	Weight  float32 `protobuf:"fixed32,2,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Muscle  float32 `protobuf:"fixed32,3,opt,name=Muscle,proto3" json:"Muscle,omitempty"`
	FatRate float32 `protobuf:"fixed32,4,opt,name=FatRate,proto3" json:"FatRate,omitempty"`
}

func (x *GetBodyByIdResponse) Reset() {
	*x = GetBodyByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBodyByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBodyByIdResponse) ProtoMessage() {}

func (x *GetBodyByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBodyByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBodyByIdResponse) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{1}
}

func (x *GetBodyByIdResponse) GetBodyid() string {
	if x != nil {
		return x.Bodyid
	}
	return ""
}

func (x *GetBodyByIdResponse) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *GetBodyByIdResponse) GetMuscle() float32 {
	if x != nil {
		return x.Muscle
	}
	return 0
}

func (x *GetBodyByIdResponse) GetFatRate() float32 {
	if x != nil {
		return x.FatRate
	}
	return 0
}

type CreateBodyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weight  float32 `protobuf:"fixed32,1,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Muscle  float32 `protobuf:"fixed32,2,opt,name=Muscle,proto3" json:"Muscle,omitempty"`
	FatRate float32 `protobuf:"fixed32,3,opt,name=FatRate,proto3" json:"FatRate,omitempty"`
}

func (x *CreateBodyRequest) Reset() {
	*x = CreateBodyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBodyRequest) ProtoMessage() {}

func (x *CreateBodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBodyRequest.ProtoReflect.Descriptor instead.
func (*CreateBodyRequest) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBodyRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateBodyRequest) GetMuscle() float32 {
	if x != nil {
		return x.Muscle
	}
	return 0
}

func (x *CreateBodyRequest) GetFatRate() float32 {
	if x != nil {
		return x.FatRate
	}
	return 0
}

type DefaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DefaultResponse) Reset() {
	*x = DefaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_body_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResponse) ProtoMessage() {}

func (x *DefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_body_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResponse.ProtoReflect.Descriptor instead.
func (*DefaultResponse) Descriptor() ([]byte, []int) {
	return file_body_proto_rawDescGZIP(), []int{3}
}

func (x *DefaultResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_body_proto protoreflect.FileDescriptor

var file_body_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x22, 0x77, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42,
	0x6f, 0x64, 0x79, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x6f, 0x64,
	0x79, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d,
	0x75, 0x73, 0x63, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x4d, 0x75, 0x73,
	0x63, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x46, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x22, 0x5d, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x75,
	0x73, 0x63, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x4d, 0x75, 0x73, 0x63,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x46, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x22, 0x29, 0x0a, 0x0f,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xcc, 0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x64, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x64, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62,
	0x6f, 0x64, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x17, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x2e, 0x62, 0x6f, 0x64, 0x79, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x62, 0x6f, 0x64, 0x79, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x62, 0x6f, 0x64, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_body_proto_rawDescOnce sync.Once
	file_body_proto_rawDescData = file_body_proto_rawDesc
)

func file_body_proto_rawDescGZIP() []byte {
	file_body_proto_rawDescOnce.Do(func() {
		file_body_proto_rawDescData = protoimpl.X.CompressGZIP(file_body_proto_rawDescData)
	})
	return file_body_proto_rawDescData
}

var file_body_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_body_proto_goTypes = []interface{}{
	(*GetByIdRequest)(nil),      // 0: body.GetByIdRequest
	(*GetBodyByIdResponse)(nil), // 1: body.GetBodyByIdResponse
	(*CreateBodyRequest)(nil),   // 2: body.CreateBodyRequest
	(*DefaultResponse)(nil),     // 3: body.DefaultResponse
}
var file_body_proto_depIdxs = []int32{
	0, // 0: body.BodyService.GetBodyById:input_type -> body.GetByIdRequest
	2, // 1: body.BodyService.CreateBody:input_type -> body.CreateBodyRequest
	0, // 2: body.BodyService.DeleteBody:input_type -> body.GetByIdRequest
	1, // 3: body.BodyService.GetBodyById:output_type -> body.GetBodyByIdResponse
	3, // 4: body.BodyService.CreateBody:output_type -> body.DefaultResponse
	3, // 5: body.BodyService.DeleteBody:output_type -> body.DefaultResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_body_proto_init() }
func file_body_proto_init() {
	if File_body_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_body_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBodyByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBodyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_body_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_body_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_body_proto_goTypes,
		DependencyIndexes: file_body_proto_depIdxs,
		MessageInfos:      file_body_proto_msgTypes,
	}.Build()
	File_body_proto = out.File
	file_body_proto_rawDesc = nil
	file_body_proto_goTypes = nil
	file_body_proto_depIdxs = nil
}
